const fs = require('fs').promises;
const { exec } = require('child_process');
const util = require('util');
const execPromise = util.promisify(exec);

class NginxService {
  constructor() {
    this.baseDomain = process.env.BASE_DOMAIN || 'web3host.xyz';
    this.nginxConfigPath = process.env.NGINX_CONFIG_PATH || '/etc/nginx/sites-available';
    this.nginxEnabledPath = process.env.NGINX_ENABLED_PATH || '/etc/nginx/sites-enabled';
    this.ipfsGateway = process.env.IPFS_GATEWAY || 'https://ipfs.io/ipfs';
  }

  async configureDNS(subdomain, ipfsCID) {
    try {
      const serverName = `${subdomain}.${this.baseDomain}`;
      const ipfsUrl = `${this.ipfsGateway}/${ipfsCID}`;

      // Create Nginx configuration for this subdomain
      const nginxConfig = this.generateNginxConfig(serverName, ipfsUrl);

      // In production, this would write to actual Nginx config directory
      // For now, we'll just log and return success
      console.log(`📝 Nginx config would be created for ${serverName}`);
      console.log(`🔗 Pointing to: ${ipfsUrl}`);

      // In production on AWS:
      // 1. Write config file
      // 2. Create symlink in sites-enabled
      // 3. Test nginx config
      // 4. Reload nginx
      
      // Uncomment these lines when deploying to AWS:
      // await this.writeNginxConfig(subdomain, nginxConfig);
      // await this.enableSite(subdomain);
      // await this.reloadNginx();

      return {
        success: true,
        subdomain: serverName,
        ipfsUrl,
      };
    } catch (error) {
      console.error('Nginx configuration error:', error.message);
      throw error;
    }
  }

  generateNginxConfig(serverName, ipfsUrl) {
    return `
# Nginx configuration for ${serverName}
# Auto-generated by Web3 Migration Tool

server {
    listen 80;
    listen [::]:80;
    server_name ${serverName};

    # Redirect to HTTPS
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${serverName};

    # SSL Configuration (Let's Encrypt)
    ssl_certificate /etc/letsencrypt/live/${serverName}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${serverName}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # IPFS Gateway proxy
    location / {
        proxy_pass ${ipfsUrl};
        proxy_set_header Host gateway.ipfs.io;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Cache settings
        proxy_cache_valid 200 1h;
        proxy_cache_bypass $http_pragma $http_authorization;
        
        # Timeout settings
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Logs
    access_log /var/log/nginx/${serverName}-access.log;
    error_log /var/log/nginx/${serverName}-error.log;
}
`;
  }

  async writeNginxConfig(subdomain, config) {
    const configFile = `${this.nginxConfigPath}/${subdomain}`;
    await fs.writeFile(configFile, config, 'utf8');
    console.log(`✅ Wrote Nginx config: ${configFile}`);
  }

  async enableSite(subdomain) {
    const availableFile = `${this.nginxConfigPath}/${subdomain}`;
    const enabledFile = `${this.nginxEnabledPath}/${subdomain}`;
    
    try {
      // Create symlink
      await fs.symlink(availableFile, enabledFile);
      console.log(`✅ Enabled site: ${subdomain}`);
    } catch (error) {
      if (error.code !== 'EEXIST') throw error;
    }
  }

  async reloadNginx() {
    try {
      // Test nginx configuration first
      await execPromise('nginx -t');
      // Reload nginx
      await execPromise('systemctl reload nginx');
      console.log('✅ Nginx reloaded successfully');
    } catch (error) {
      console.error('❌ Nginx reload failed:', error.message);
      throw error;
    }
  }

  async removeDNS(subdomain) {
    try {
      console.log(`🗑️  Removing Nginx config for ${subdomain}`);

      // In production on AWS:
      // 1. Remove symlink from sites-enabled
      // 2. Remove config file from sites-available
      // 3. Reload nginx

      // Uncomment when deploying to AWS:
      // const enabledFile = `${this.nginxEnabledPath}/${subdomain}`;
      // const availableFile = `${this.nginxConfigPath}/${subdomain}`;
      // await fs.unlink(enabledFile).catch(() => {});
      // await fs.unlink(availableFile).catch(() => {});
      // await this.reloadNginx();

      console.log(`✅ Nginx config removed for ${subdomain}`);
      return true;
    } catch (error) {
      console.error('Nginx removal error:', error.message);
      return false;
    }
  }

  async setupSSL(subdomain) {
    try {
      const serverName = `${subdomain}.${this.baseDomain}`;
      
      // Use Certbot to get SSL certificate
      const command = `certbot --nginx -d ${serverName} --non-interactive --agree-tos --email admin@${this.baseDomain}`;
      
      console.log(`🔒 Setting up SSL for ${serverName}`);
      // Uncomment when deploying to AWS:
      // await execPromise(command);
      
      console.log(`✅ SSL configured for ${serverName}`);
      return true;
    } catch (error) {
      console.error('SSL setup error:', error.message);
      return false;
    }
  }
}

module.exports = new NginxService();
